//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetAccounting.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoConsumables
    {
        public int IdInfoC { get; set; }
        public string InfoC { get; set; }
        public string SizeC { get; set; }
    }
}
