//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetAccounting.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicines
    {
        public int IdMedicines { get; set; }
        public string NameMedicines { get; set; }
        public string ManufacturerMedicines { get; set; }
        public string QuantityMedicines { get; set; }
        public string RemainsMedicines { get; set; }
        public System.DateTime DateOfReceiptMedicines { get; set; }
        public string ExpirationDateMedicines { get; set; }
        public byte[] PhotoMedicines { get; set; }
        public int IdStaff { get; set; }
        public string InfoMedicines { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
