//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetAccounting.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int IdPurchase { get; set; }
        public string ProvidePurchaser { get; set; }
        public string CostPurchase { get; set; }
        public string StatysPurchase { get; set; }
        public string NumberProvidePurchase { get; set; }
        public int IdStaff { get; set; }
        public int IdType { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Type Type { get; set; }
    }
}
